name: kwayes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+17

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_auth: 
  google_sign_in: ^5.0.7
  flutter_facebook_auth: ^3.5.0
  shared_preferences: ^2.0.5
  the_apple_sign_in: ^1.1.1
  flutter_svg: ^0.22.0
  video_player: ^2.1.15
  firebase_storage: ^8.1.3
  google_maps_flutter:
  swipe_to: ^0.0.1+8
  camera: ^0.9.4+3
  path_provider:
  path:
  geolocator: ^5.3.1
  cached_network_image: ^3.1.0
  file_picker: ^3.0.2+2
  geocoding: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/logo.png
    - assets/images/icons/
    - assets/images/backgrounds/
    - lib/lang/ar.json
    - lib/lang/en.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
    - family: DIN
      fonts:
        - asset: assets/fonts/din/DINNextLTArabicRegular.ttf
        - asset: assets/fonts/din/DINMedium.ttf
          weight: 500
    - family: Futura BdCn BT
      fonts:
        - asset: assets/fonts/futura_bdcn_bt/FuturaBoldCondensedBT.ttf
