name: kwayes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  provider: ^6.0.0
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.0
  flutter_facebook_auth: ^3.5.1
  the_apple_sign_in: ^1.1.1
  flutter_svg: ^0.22.0
  video_player: ^2.2.4
  visibility_detector: ^0.2.0
  firebase_storage: ^10.0.3
  google_maps_flutter: ^2.0.10
  geocoding: ^2.0.1
  swipe_to: ^0.0.1+8
  better_player: ^0.0.73



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/logo.png
    - assets/images/icons/
    - assets/images/backgrounds/
    - lib/lang/ar.json
    - lib/lang/en.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
    - family: DIN
      fonts:
        - asset: assets/fonts/din/DINNextLTArabicRegular.ttf
        - asset: assets/fonts/din/DINMedium.ttf
          weight: 500
    - family: Futura BdCn BT
      fonts:
        - asset: assets/fonts/futura_bdcn_bt/FuturaBoldCondensedBT.ttf
